### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by nphaterp** [UBC-MDS/covid-19-cases-vs-tests-analysis#1]

**Comment by nphaterp** [comment]
**Notes for Nov.18 Meeting (Lab Session):**

**Items Addressed:**

- Introductions, discussed individual backgrounds/strenghts/weaknesses 
- Discuss group contract
- Create Project Repo
- Fork Repositories
- Discuss tasks for Milestone 1 
- Decide on Data set

**Dividing up tasks:**
- Tanmay will complete/polish up the group contract
- Neel will complete Code-of-conduct document
- Fatime will complete the licencing and contribution document

**Deciding on Data Sets**
- No strong feelings about the subject matter of the data, but would prefer current/relevant data sets (election, COVID, etc.)
- We want to perform inferential analysis instead of predicitve analysis for this project 
- Several links were shared and explored but we did not have time to decide on one together. 

**Plans for next meeting:** 
- Decide on data set 
- Divide the next tasks that are relevant to Milestone 1

**Comment by nphaterp** [comment]
Not sure if I covered everything there ^ I only started taking notes about halfway through meeting.

**Comment by nphaterp** [comment]
**Notes for Nov.18 Meeting (Evening Session):**
This was a short meeting to discuss the data sets. 

- We decided that we would proceed with the data found at  https://github.com/owid/covid-19-data/tree/master/public/data

- We decided that we will perform analysis (likely a hypothesis test) checking if there is a difference in a certain feature between two countries (possibly Canada vs. ?). 

- We are going to take the evening to think of a meaningful, yet easy question for our analysis. This includes deciding the countries and the feature that we are interested in. 

- We are going to vote on these questions tomorrow after 2pm.

**Comment by nphaterp** [comment]
**Notes for Nov.20 Meeting (Morning Session):**

- We finalized our question for analysis
- We divided up the remainder of work as follows: 

Nick + Tanmay - perform EDA 
Neel - Create project proposal (Q3-5)
Fatime - Complete other things required for README file (milestone1) + Q1,2 for proposal

Our next meeting will be on Nov.20 at 630 pm.

**Comment by nphaterp** [comment]
**Notes for Nov.20 Meeting (Evening Session):**

- We went over the EDA files 
- **we changed the response_ratio to be # of daily tests/ # daily cases**
- We agreed that everyone will review the proposal before merging PR
- We will finish our parts by the end of the night (ie. when Tanmay finally hits the sack) 

- Meeting (10am) to finalize Milestone 1.

**Comment by tanmaysharma19** [comment]
**Nov.24, 6 PM Meeting.**
In attendance: Neel, Nicholas, Fatime, Tanmay

**Agenda:**
-  6.00 - 6.15 PM - Retrospective about M1 
- 6.15 - 7:00 PM - M2 planning  - Workload distribution 

**Meeting Minutes:**

_Retro: What went well?_

Fatime:
- Good communication, always updated about team's progress
- Team members were responsive to PRs
Neel:
- Worked as a team
- environment of respect
Tanmay:
- positive environment, helping each other
- Saturday session to review and submit as a team
- Should continue using checklists for project tracking and task ownership

_Retro: What can be improved?_

Fatime:
- distribution of workload
- better pace progress throughout the week to allow for reviewing work more thoroughly
- more opportunities for pair-programming
Neel:
- late start on Milestone 1, start earlier in the week
Tanmay:
- Task ownership outlined earlier in the week with everyone's agreement
- Continue using the project tracker/ checklist

_M2 -Task Distribution_
- The team reviewed Milestone 2 requirements.
- All M2 expectations were collated in a checklist document.
- Task owners were defined after due deliberation.
- Agreed on starting work on all scripts tomorrow and for collaborating through PRs and feedback. 

[dsci-522-weekly-Milestone-checklist-Group24 - Milestone2.pdf](https://github.com/UBC-MDS/covid-19-cases-vs-tests-analysis/files/5594198/dsci-522-weekly-Milestone-checklist.-.Milestone2.pdf)

**Comment by tanmaysharma19** [comment]
**Nov.27, 11 AM Meeting.**
In attendance: Neel, Nicholas, Fatime, Tanmay

**Agenda:**

1. Discuss TA's feedback for M1
2. Discussion about limitations/ future work
3. Review status of all open work items
4. Finalize submission plan for M2

**Meeting Minutes:**

1. Discussed TA's feedback regarding temporal nature of data.
2. Discussed feedback regarding not pushing csv files to data folder.
3. Formulated questions for the TA to seek clarity on M1 grade and feedback regarding above 2 points.
4. Decided to reach out to TA over Slack as per point 3 above.
5. Discussed potential limitations of the statistical question and what to include in the summary report.
6. Deferred agenda items 3 and 4 to an evening meeting for 6pm.

**Comment by tanmaysharma19** [comment]
**Nov.27, 6 PM Meeting.**
In attendance: Neel, Nicholas, Fatime, Tanmay

**Agenda:**

1. Merge PR for script4 and ensure there are no conflicts
2. Discuss team’s preference for the plots and tables to be included in the Summary Report.
3. Visit the checklist and review status of all open work items
4. Finalize work and timeline for submission of Milestone-2.

**Meeting Minutes:**

1. Resolved merge conflicts arising due to the PR for script4.
2. Reviewed and updated some edits to script4 for plot creations.
3. Reviewed and edited the Readme file to include updated usage instructions.
4. Decided on the plots and table to be included in the summary report.
5. Reviewed the summary report.
6. Closed all open PRs other than the summary report.
7. Deferred agenda items 3 and 4 to a morning 11AM meeting for November 28th.

**Comment by tanmaysharma19** [comment]
**Nov.28, 11 AM Meeting.**
In attendance: Neel, Nicholas, Fatime, Tanmay

**Agenda:**

1. Review final report and make necessary changes - close PR #48.
2. Review and close PR #49.
3. Visit the checklist (Issue #26) and review status of all open work items.
4. Update Readme.md to change usage instructions for final report.
5. Update Script 4 code to change title of “Figure 1” to exclude the caption numbering.
6. Finalize work and submit Milestone-2.

Minutes:
The team had a working session and all the agenda items were discussed and associated work items closed.

**Comment by nichowu** [comment]
2020-12-01

Meeting Minutes:

1. M3 checklist is now setup on googledocs.
2. Work item distributed. 
3. Agreed that we will write the Makefile in R, as advised by Tiffany.
4. Agreed that we will need to include function testing in scripts.
5. Next meeting: Wednesday 12-02-2020 at 6:00pm

**Comment by nichowu** [comment]
2020-12-02 Lab Session Meeting:

1. Raw data file wasn't downloaded/processed correctly due to source file being updated daily and now it is too big for R to infer data type correctly. Problem was solved by adding 'guess_max' in read_csv in download_data.R. An issue was also created as advised by Hossam (TA) to inform M2 markers about this problem. 
2. Group reviewed Makefile. Changed final output to .pdf for Latex to render correctly. Fixed p-value image's font size. 
3. As advised by Tiffany, we will not be including EDA report in Makefile. 
4. Fatime will send two PRs later today. One to fix download script and the other to upload makefile. 

Next meeting: Friday morning 2020-12-04. Time: TBA
